config/routes.rb
Rails.application.routes.draw do
  # get 'restaurants', to: 'restaurants#index'
  # get 'restaurants/new', to: 'restaurants#new'
  # get 'restaurants/:id', to: 'restaurants#show', as: :restaurant
  # post 'restaurants', to: 'restaurants#create'
  # get 'restaurants/:id/edit', to: 'restaurants#edit', as: :edit_restaurant
  # patch 'restaurants/:id', to: 'restaurants#update'
  # delete 'restaurants/:id', to: 'restaurants#destroy'
  resources :restaurants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update destroy]

  def index
    # get all the restaurant instances from db
    # assign that to an instance variable to pass it onto the view
    @restaurants = Restaurant.all
  end

  def show; end

  def new
    @restaurant = Restaurant.new
  end

  def create
    strong_params = restaurant_params
    @restaurant = Restaurant.new(strong_params)
    # save the instance to the DB
    @restaurant.save

    redirect_to restaurant_path(@restaurant)
  end

  def edit
    # find the instance of the restaurant we want to edit
    # assign that to an instance variable and pass it onto view
  end

  def update
    # we give the new params to the insatnce
    # we save the changes to the DB
    @restaurant.update(restaurant_params)
    # redirect the user to the show page
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    # destroy method onto that instance
    @restaurant.destroy

    # redirect the user to the index page
    redirect_to restaurants_path, status: :see_other
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :rating, :address)
  end

  def set_restaurant
    # find the instance with the ID
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCrud1343</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_with model: restaurant do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.label :address %>
  <%= form.text_field :address %>
  <%= form.label :rating %>
  <%= form.number_field :rating %>
  <%= form.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>I'm in edit</h1>
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h1>Restaurants#index</h1>
<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <h3>
        <%= link_to restaurant.name, restaurant_path(restaurant) %>
      </h3>
      <p>📭 <%= restaurant.address %></p>
    </li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<h1>Create a restaurant!</h1>
<%= form_with model: @restaurant do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.label :address %>
  <%= form.text_field :address %>
  <%= form.label :rating %>
  <%= form.number_field :rating %>
  <%= form.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1>📛 <%= @restaurant.name %></h1>
<h3>
  📭 <%= @restaurant.address %>
</h3>
<p>
  <% @restaurant.rating.times do %>
    ⭐️
  <% end %>
</p>
<%= link_to "Delete Restaurant",
  restaurant_path(@restaurant),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>
<%= link_to "Edit", edit_restaurant_path(@restaurant) %>